# This file is machine-generated - editing it directly is not advised

[[Mocking]]
git-tree-sha1 = "bd2623f8b728af988d2afec53d611acb621f3bc4"
uuid = "78c3b35d-d492-501b-9361-3d52fe80e533"
version = "0.7.0"
