name = "SpecializeVarargs"
uuid = "24973c7f-061f-47f0-b8d1-653b711ffc2d"
authors = ["MasonProtter <mason.protter@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
