name = "SpecializeVarargs"
uuid = "24973c7f-061f-47f0-b8d1-653b711ffc2d"
authors = ["MasonProtter <mason.protter@gmail.com>"]
version = "0.1.0"

[deps]
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"

[compat]
julia   = "1"
Mocking = "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
