name = "SpecializeVarargs"
uuid = "24973c7f-061f-47f0-b8d1-653b711ffc2d"
authors = ["MasonProtter <mason.protter@gmail.com>"]
version = "0.1.1"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"

[compat]
ExprTools = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
